import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title key="title ">Rick and Morty NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <h1>HomePage</h1>
        {/* <Image
          src={
            "https://m.media-amazon.com/images/M/MV5BZjRjOTFkOTktZWUzMi00YzMyLThkMmYtMjEwNmQyNzliYTNmXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_FMjpg_UX1000_.jpg"
          }
          alt="rickandmortyhomeimage"
          width={100}
          height={100}
        /> */}
        <p>
          I'm learning about rendering styles in Next.js - this page was
          Statically Rendered by default. The Characters page is rendered
          Server-Side and shows a list of Rick and Morty characters. From there,
          you can click each character to follow a Statically-Generated path,
          and visit Character page rendering with Static-Site-Generation. I've
          fetched the data for these pages from a REST API. The Episodes page is
          rendered Client-Side. I've used a filtered GraphQL query to fetch the
          data. Here is a good article to help you use Graph QL together with
          the Fetch API.
        </p>
        <Link href={"/characters"}>View Characters</Link>
      </main>
    </div>
  );
}
